### ISSUE TITLE
Result::unwrap()` on an `Err` value: NotPresent'

### ISSUE THREAD

**Issue by Tsunayoshi** [reminder-bot/timezone-dispatch#1]
Hello,

I tried to made this work on my timeserver but i get an error msg.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MySqlError { ERROR 1054 (42S22): Unknown column 'guild' in 'field list' }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: timezone_dispatch::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: main
  15: __libc_start_main
  16: _start
```

I already found out that a missing coulm "guild" cause an error and just added that to the mysql table but then i get another error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: timezone_dispatch::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: main
  15: __libc_start_main
  16: _start
```

I cant solve that. I already tried diffrent values on the guild field but nothing change.

Edit: The Time of the channel change 1 time on execute (with and without guild field) but after that it stops.

**Comment by JellyWX** [comment]
Have you got a suitable `.env` file set up with environment variables?

⁣Get BlueMail for Android ​

**Comment by Tsunayoshi** [comment]
DISCORD_TOKEN="i removed token"
SQL_URL="mysql://timezone:i removed password@localhost/timezone"
INTERVAL=20
THREADS=4

if i start it with ./timezone-bot the discord channel get an update 1 time so the connection should be fine, since he get channel id and format from the mysql db

**Comment by JellyWX** [comment]
Is the issue only occuring when running the program as a daemon? If so, is the daemon's configuration file set so that the run location is the same folder containing the .env file?

⁣Get BlueMail for Android ​

**Comment by Tsunayoshi** [comment]
the daemon doesnt run it seem. not even change the channel.
using the command directly makes the error msg pop but still change the channel name.
crontab also doesnt work :(

EDIT:```

[Unit]
Description=Timezone Bot

[Service]
Type=simple
ExecStart=/timezone-bot/timezone-dispatch
WorkingDirectory=/timezone-bot/
Restart=always
RestartSec=4

[Install]
WantedBy=sysinit.target
```

**Comment by Tsunayoshi** [comment]
just saw daemon.log:

```
Oct 14 20:18:30 time systemd[1]: Started Timezone Bot.
Oct 14 20:18:30 time timezone-dispatch[81689]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MySqlError { ERROR 1054 (42S22): Unknown column 'guild' in 'field list' }', src/libcore/result.rs:997:5
Oct 14 20:18:30 time timezone-dispatch[81689]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Oct 14 20:18:30 time systemd[1]: timezone-bot.service: Main process exited, code=exited, status=101/n/a
Oct 14 20:18:30 time systemd[1]: timezone-bot.service: Unit entered failed state.
Oct 14 20:18:30 time systemd[1]: timezone-bot.service: Failed with result 'exit-code'.
Oct 14 20:18:34 time systemd[1]: timezone-bot.service: Service hold-off time over, scheduling restart.
Oct 14 20:18:34 time systemd[1]: Stopped Timezone Bot.
Oct 14 20:18:34 time systemd[1]: Started Timezone Bot.
Oct 14 20:18:34 time timezone-dispatch[81703]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MySqlError { ERROR 1054 (42S22): Unknown column 'guild' in 'field list' }', src/libcore/result.rs:997:5
Oct 14 20:18:34 time timezone-dispatch[81703]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Oct 14 20:18:34 time systemd[1]: timezone-bot.service: Main process exited, code=exited, status=101/n/a
Oct 14 20:18:34 time systemd[1]: timezone-bot.service: Unit entered failed state.
Oct 14 20:18:34 time systemd[1]: timezone-bot.service: Failed with result 'exit-code'.
Oct 14 20:18:38 time systemd[1]: timezone-bot.service: Service hold-off time over, scheduling restart.
Oct 14 20:18:38 time systemd[1]: Stopped Timezone Bot.
Oct 14 20:18:38 time systemd[1]: Started Timezone Bot.
Oct 14 20:18:38 time timezone-dispatch[81717]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MySqlError { ERROR 1054 (42S22): Unknown column 'guild' in 'field list' }', src/libcore/result.rs:997:5
Oct 14 20:18:38 time timezone-dispatch[81717]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Oct 14 20:18:38 time systemd[1]: timezone-bot.service: Main process exited, code=exited, status=101/n/a
Oct 14 20:18:38 time systemd[1]: timezone-bot.service: Unit entered failed state.
Oct 14 20:18:38 time systemd[1]: timezone-bot.service: Failed with result 'exit-code'.
Oct 14 20:18:43 time systemd[1]: timezone-bot.service: Service hold-off time over, scheduling restart.
Oct 14 20:18:43 time systemd[1]: Stopped Timezone Bot.
```

**Comment by Tsunayoshi** [comment]
could it be that part?

```
        let mut unique = mysql_conn.prep_exec("SELECT COUNT(DISTINCT(guild)) FROM clocks", ()).unwrap();

        match unique.next() {
            Some(row) => {
                let mut d = HashMap::new();

                d.insert("server_count", mysql::from_row::<(u32)>(row.unwrap()));

                let _  = req_client.post(&format!("https://discordbots.org/api/bots/{}/stats", env::var("ID").unwrap()))
                    .json(&d)
                    .header("Content-Type", "application/json")
                    .header("Authorization", env::var("DBL_TOKEN").unwrap())
                    .send();
            }

            None => {}
}
```

**Comment by JellyWX** [comment]
Ah yes, its the env::var call I think.

Add a blank ID field to the .env 

⁣Get BlueMail for Android ​

**Comment by Tsunayoshi** [comment]
Yeah! That was the right idea :)
I added:
"guild" to the mysql table
and
ID=""
DBL_TOKEN=""

to then .env file

now its perfectly working! thank you for your time!!!

**Comment by JellyWX** [comment]
Perfect! Can you close this please, since I'm replying to this through email?

Thanks

⁣Get BlueMail for Android ​

**Comment by Tsunayoshi** [comment]
Sure :)
